global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "conduit"

    metrics_path: /metrics

    static_configs:
      - targets:
          - api1:8081
          - api2:8081
          - api3:8081
